### ISSUE TITLE
Flag emoji can destroy an entire menu

### ISSUE THREAD

**Issue by jmfergeau** [PHPBoost/PHPBoost#156]
I found a very very wrong glitch.

To do this, make a new link menu, add a menu entry and on the menu entry name, add a flag emoji (like this one 🇬🇧).

the whole website will report the following fatal error:

```
Fatal error: Uncaught Error: Call to a member function id() on bool in /srv/data/web/vhosts/sonic.maxlefou.com/htdocs/kernel/framework/phpboost/menu/MenuService.class.php:627 Stack trace: #0 /srv/data/web/vhosts/sonic.maxlefou.com/htdocs/kernel/framework/phpboost/menu/MenuService.class.php(52): MenuService::initialize() #1 /srv/data/web/vhosts/sonic.maxlefou.com/htdocs/kernel/framework/phpboost/cache/MenusCache.class.php(23): MenuService::get_menu_list() #2 /srv/data/web/vhosts/sonic.maxlefou.com/htdocs/kernel/framework/io/data/cache/CacheManager.class.php(77): MenusCache->synchronize() #3 /srv/data/web/vhosts/sonic.maxlefou.com/htdocs/kernel/framework/phpboost/cache/MenusCache.class.php(44): CacheManager::load() #4 /srv/data/web/vhosts/sonic.maxlefou.com/htdocs/kernel/framework/io/template/data/DefaultTemplateData.class.php(71): MenusCache::load() #5 /srv/data/web/vhosts/sonic.maxlefou.com/htdocs/kernel/framework/io/template/FileTemplate.class.php(44): DefaultTemplateData->auto_load_frequent_vars() #6 /srv/data/web/vhosts/sonic.maxlefou.com/htdocs/user/controllers/UserErrorController.class.php(100): FileTemplate->__construct() #7 /srv/data/web/vhosts/sonic.maxlefou.com/htdocs/user/controllers/UserErrorController.class.php(77): UserErrorController->create_view() #8 /srv/data/web/vhosts/sonic.maxlefou.com/htdocs/kernel/framework/core/error/ExceptionHandler.class.php(116): UserErrorController->execute() #9 /srv/data/web/vhosts/sonic.maxlefou.com/htdocs/kernel/framework/core/error/ExceptionHandler.class.php(104): ExceptionHandler->integrated_display() #10 /srv/data/web/vhosts/sonic.maxlefou.com/htdocs/kernel/framework/core/error/ExceptionHandler.class.php(57): ExceptionHandler->send_response() #11 /srv/data/web/vhosts/sonic.maxlefou.com/htdocs/kernel/framework/core/error/ExceptionHandler.class.php(34): ExceptionHandler->display() #12 [internal function]: ExceptionHandler->handle() #13 {main} thrown in /srv/data/web/vhosts/sonic.maxlefou.com/htdocs/kernel/framework/phpboost/menu/MenuService.class.php on line 627
```
And when I checked on the database, it visibly **destroyed** the menu ! To fix it, I had to delete the incriminated menu manually in the database. Good thing it was a small menu !

Maybe either add support for emojis for that, or find a way to throw a more friendly error if an emoji is detected ?...

**Comment by babsolune** [comment]
for PHPBoost, the better way is to set an utf-8 database, and in anycase, emojis are characters from the UTF-8 character set

**Comment by jmfergeau** [comment]
Maybe it would be good to add this information in documentation, eventually?

**Comment by MaxenceCauderlier** [comment]
@babsolune Can you put an emoji on a menu ? I think it's impossible cause menus datas are serialized. 
I tested with a DB in utf8mb4general_ci and I have this : 

```
MySQLQuerierException
invalid query. (ERRNO 1366) Incorrect string value: '\xF0\x9F\x9A\xA9";...' for column 'object' at row 1query: UPDATE phpboost_menus SET title='PHPBoost', object='O:9:\"LinksMenu\":21:{s:4:\"type\";s:9:\"automatic\";s:8:\"elements\";a:22:{i:0;O:13:\"LinksMenuLink\":19:{s:3:\"url\";s:6:\"/news/\";s:5:\"image\";s:0:\"\";s:4:\"icon\";s:22:\"far fa-fw fa-newspaper\";s:3:\"uid\";i:1765;s:5:\"depth\";i:1;s:2:\"id\";i:0;s:5:\"title\";s:16:\"Actualités 🚩\";s:4:\"au....
```

Maybe later with data serialized by json ;)
